module Madmin
  # Paginates ActiveRecord relations using only the relation API (count, order,
  # offset, limit) so the SQL is generated by whichever database adapter is in use.
  module Pagination
    private

    # Returns [Madmin::Page, records]
    def paginate(collection, page: 1, per_page: Madmin.per_page, param: :page)
      page = Madmin::Page.new(count: count_for(collection), page: page, per_page: per_page, param: param)
      [page, with_tiebreaker(collection).offset(page.offset).limit(page.per_page)]
    end

    def count_for(collection)
      # count(:all) keeps custom selects valid, and ordering is irrelevant to a count
      count = collection.unscope(:order).count(:all)

      # Grouped relations return a Hash of counts per group
      count.is_a?(Hash) ? count.size : count
    end

    # Appends the primary key to the ordering so rows with equal sort values keep
    # a stable position across pages. It follows the direction of the existing
    # ordering so indexes on the sort column can still be used.
    def with_tiebreaker(collection)
      return collection if collection.group_values.any? || collection.distinct_value

      primary_keys = Array(collection.klass.primary_key).map(&:to_s)
      return collection if primary_keys.empty?

      orders = collection.order_values
      return collection if orders.any? { |order| orders_by?(order, primary_keys) }

      direction = descending?(orders.last) ? :desc : :asc
      table = collection.klass.arel_table
      collection.order(primary_keys.map { |key| table[key].public_send(direction) })
    end

    def orders_by?(order, column_names)
      order.is_a?(Arel::Nodes::Ordering) && order.expr.respond_to?(:name) && column_names.include?(order.expr.name.to_s)
    end

    def descending?(order)
      case order
      when Arel::Nodes::Descending then true
      when String then order.match?(/\bdesc\s*\z/i)
      else false
      end
    end
  end
end
